### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by AlexanderSamokhin** [Tulpep/Active-Directory-Object-Picker#14]
Please provide functionality to setup User/Password to IDsObjectPicker

Usage of IDsObjectPickerCredentials :
https://msdn.microsoft.com/en-us/library/cc185676(v=vs.85).aspx

**Comment by ricardopolo** [comment]
@AlexanderSamokhin What about a run as?
In case that does not work for you, would you help us with a PR? I am willing to approve it

**Comment by AlexanderSamokhin** [comment]
"run as" - this isn't the solution. I have to connect to several domains. And as I told on c++ it is works brilliant (example on link above)

**Comment by ricardopolo** [comment]
Righ now I cannot implement it for time restrictions.I am sorry about that. If you can implement it I will happy accept a PR and release a new NuGet version

**Comment by ricardopolo** [comment]
@dahall this is issue is fixed with your PR, right? In your opinion we should close this one?

Thanks

**Comment by dahall** [comment]
I corrected this issue in my PR. You are welcome to close it.
