### ISSUE TITLE
Assign values to the object selection area by default

### ISSUE THREAD

**Issue by poweredbyporkers** [Tulpep/Active-Directory-Object-Picker#16]
Say I want to search for JSMITH, is there a property to assign this directly into the 'Enter the object names to select' area?

I know I can open it and type in JSMITH, but I already have the JSMITH value in the dataset and assigning it directly would be awesome as it might be JSMITH;JDOE;BCLINTON etc.

**Comment by ricardopolo** [comment]
If you manage to do that I'll be willing to accept your PR. Best regards!!

**Comment by dahall** [comment]
I have done quite a bit of research into this and have determined that there is not a mechanism supported by the Microsoft API to do this. The IDsObjectPicker interface has an Initialize method, but the structure passed in as a parameter does not have a value associated with the initially selected object.
