### ISSUE TITLE
Get rid of ActiveDs.dll?

### ISSUE THREAD

**Issue by fgreinacher** [Tulpep/Active-Directory-Object-Picker#18]
`ActiveDs.dll` only seems to be used by `Active-Directory-Object-Picker/Tulpep.ActiveDirectoryObjectPicker/NameTranslator.cs` which in turn is only be used by `Active-Directory-Object-Picker/ADPickerTester/MainForm.cs`. 

Therefore it seems that `NameTranslator` could be moved to `ADPickerTester` which in turn would make `ActiveDs.dll` obsolete in the NuGet package. 

Would you accept a PR that get rid of this dependency chain?

**Comment by ricardopolo** [comment]
@fgreinacher good catch!

Do it, If it works I'll approve it and release a new version
