### ISSUE TITLE
.NET Versions, NuGet and Symbols

### ISSUE THREAD

**Issue by dahall** [Tulpep/Active-Directory-Object-Picker#23]
Issues #17 and #21 both asked for different versions. I'm specifically asking for a common NuGet model of deploying multiple libraries compiled to different versions and also include symbol files and XML documentation to help with writing and debugging. I have forked and made the changes to the project file (allowing for compiling against .NET versions 2.0, 3.5, 4.0 and 4.5.2) along with the changes to product debug (PDB) and XML documentation files and am about to submit a pull request. I have also added support for credentials (Issue #14) and have changed the project, where applicable, to remove simple properties to auto-properties.

**Comment by adriencarbonne** [comment]
Hello, when do you plan to update the NuGet package so it can work on .NET 2.0?
Everything looks fine code-wise.

**Comment by ricardopolo** [comment]
We'll be realasing a new version later today.

@codingneat we need to upgrade the digital certificate today, so the continues integration server release a new version!

**Comment by ricardopolo** [comment]
@adriencarbonne I was trying to make it work but it does not work. It was not related to digital signatures or nuget api keys, that I intially thought.

Thie build is failing due this line added by you
https://github.com/Tulpep/Active-Directory-Object-Picker/blob/e4b2fa7aa071567820fe0c8a91768eef08a36fb4/Tulpep.ActiveDirectoryObjectPicker/Tulpep.ActiveDirectoryObjectPicker.csproj#L140

Can you help us checking why this fail?
Here you can see the build log https://ci.appveyor.com/project/tulpep/active-directory-object-picker

Thank you!

**Comment by dahall** [comment]
That conditional to only include the file when building against .NET Framework versions less than 3.5 works on every VS project since VS 2010. What is building it in your build chain?

**Comment by dahall** [comment]
I looked at the build log and would suggest changing that line (140) to:
`<Compile Include="ExtensionAttributeFor.NET_2.0.cs" Condition="  '$(Framework)' == 'NET20' " />`
According to the web, this will work with the MSBuild 12 engine being used.

**Comment by ricardopolo** [comment]
@dahall Done in https://github.com/Tulpep/Active-Directory-Object-Picker/commit/19fd70268cbdd3b2baa7256c90a2b9bd51b8c666

Still fails, not working in .NET 2.0 
https://ci.appveyor.com/project/tulpep/active-directory-object-picker/build/2.1.121

**Comment by dahall** [comment]
The following line works with MSBuild 15.x:
`<Compile Include="ExtensionAttributeFor.NET_2.0.cs" Condition=" $(TargetFrameworkVersion.Replace(&quot;v&quot;,&quot;&quot;)) == 2.0 " />`

**Comment by ricardopolo** [comment]
@dahall after mount pleasant changes it is working. Just release a new version.  Please confirm it works as you expect so we cena close the issue. 

Thanks for all your help!

**Comment by ricardopolo** [comment]
@adriencarbonne a new nugget  version was released!

**Comment by adriencarbonne** [comment]
Hello Ricardo,

I have tested it in my VS solution and it is working fine now.
Thank you very much!

Adrien Carbonne
