### ISSUE TITLE
Can not find attributes such as SID of machine when use FQDN

### ISSUE THREAD

**Issue by shanx330** [Tulpep/Active-Directory-Object-Picker#26]
Hi, I meet an issue that it can not find attributes such as SID of machine when use FQDN. Short name works fine. Is this an expected behavior? Is there any workaround?
Thanks.

**Comment by ricardopolo** [comment]
Definitely not  a excepect behavior..
Right now I dont have time to check this, im sorry about this. If you found any clue about what is happening in your enviroment or submit a PR about this issue I will happy to merge it.

Thanks

**Comment by ricardopolo** [comment]
@shanx330 closing due not active. Please feel free to reopen if necessary.
