### ISSUE TITLE
Allow user to pass in initial selection

### ISSUE THREAD

**Issue by MCFHTAGENTS** [Tulpep/Active-Directory-Object-Picker#27]
Looking at this API please can it be enhanced such that you can pass in a AD Object and this becomes the initial selection.
Thanks
Mark

**Comment by ricardopolo** [comment]
I don’t have to implement this feature now. However, if you can make a Pr that makes that I will be happy to approve it and release a new nugget version. 

Thanks

**Comment by dahall** [comment]
Duplicate of #16

**Comment by ricardopolo** [comment]
Closing this. Lets talk in #16
