### ISSUE TITLE
Can i open advance view directly

### ISSUE THREAD

**Issue by PRERNA14** [Tulpep/Active-Directory-Object-Picker#28]
is it possible to open advance view directly?

**Comment by PRERNA14** [comment]
Anyone please provide this solution.

**Comment by dahall** [comment]
Looking at the options on the native DSOP_INIT_INFO structure used with the IDsObjectPicker::Initialize method, there does not appear to be a way to specify the Advanced View as the initial view.

**Comment by ricardopolo** [comment]
I don think that Windows API allows that 😢

**Comment by PRERNA14** [comment]
Hey
I want to retrieve some other information from the selected object like
department telephone no,full name..how can i do the same

**Comment by dahall** [comment]
It is very easy. Supply the additional attributes as strings to the `AttributesToFetch` property. A good list of those attributes is at http://www.kouti.com/tables/userattributes.htm. Once you have called the dialog, the results are all in the `SelectedObject` or `SelectedObjects` property results in the `FetchedAttributes` property. They will be in the order of the strings provided in `AttributesToFetch`.
