### ISSUE TITLE
Why it is slow in Windows 7

### ISSUE THREAD

**Issue by PRERNA14** [Tulpep/Active-Directory-Object-Picker#29]
Why it is slow in window 7 os

**Comment by dahall** [comment]
This library calls native library functions. If you are experiencing slow response times, it is likely due to how your Windows 7 device is connected to the domain, specifically the domain controller.

**Comment by PRERNA14** [comment]
So how can i change that

**Comment by dahall** [comment]
Network latency seems to have a significant effect as the DS methods a chatty. It is also possible that your domain controller is overloaded or also having network problems. If the DC is not available at all, then every call to this library will wait for a network timeout before responding with cached information.

**Comment by PRERNA14** [comment]
Hey David
I have one more question
How can i get other properties of a user like department,full name,
description from the selectedobject  object

**Comment by ricardopolo** [comment]
Fixed by #35
