### ISSUE TITLE
SID for BuiltIn group is wrong

### ISSUE THREAD

**Issue by B4DschK4Pp** [Tulpep/Active-Directory-Object-Picker#33]
Hi,
when i query the objectSID for a BuiltIn group the SID has a wrong format and the string is different to what is actually in the objectSID attribute in AD.
This only occurs with BuiltIn groups.
![image](https://user-images.githubusercontent.com/26527958/68023248-f06da900-fca6-11e9-993b-255b85c074f2.png)

Am I missing something?

Sebastian

**Comment by MarcelGosselin** [comment]
The problem was unrelated to BuiltinGroups but more to the fact that the SID had 16 bytes and was displayed as a Guid instead.
