### ISSUE TITLE
Sign the assembly with a strong name key file

### ISSUE THREAD

**Issue by snarfblatt** [Tulpep/Active-Directory-Object-Picker#9]
We enforce strong name's for all assemblies we reference. It would be great if this assembly was also signed.

**Comment by ricardopolo** [comment]
Will do it!

**Comment by ricardopolo** [comment]
@snarfblatt we have upload  a pre release version with Strong Name.
https://www.nuget.org/packages/Tulpep.ActiveDirectoryObjectPicker/1.0.27-beta

Please test it and say if is what you need. Then we'll release and stable version with strong name sign!

**Comment by snarfblatt** [comment]
This worked great. Thanks.

**Comment by ricardopolo** [comment]
I'll open until we release a final version

**Comment by snarfblatt** [comment]
Ah sorry.

**Comment by molnarm** [comment]
This has been open for almost a year now, can we have a signed version please?

**Comment by ricardopolo** [comment]
@molnarm later today today I'll publish it

**Comment by ricardopolo** [comment]
@molnarm meanwhile you can use the beta version (https://www.nuget.org/packages/Tulpep.ActiveDirectoryObjectPicker/1.0.27-beta) that is already signed.
